// Mocks generated by Mockito 5.4.5 from annotations
// in realtime_innovations_test/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:realtime_innovations_test/data/dao/employee_account/employee_account_dao.dart'
    as _i6;
import 'package:realtime_innovations_test/domain/dao_controller/employee_account/employee_account_dao_controller.dart'
    as _i2;
import 'package:realtime_innovations_test/domain/repository/manage_employee/config/manage_employee_config.dart'
    as _i5;
import 'package:realtime_innovations_test/domain/repository/manage_employee/manage_employee_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEmployeeAccountDaoController_0 extends _i1.SmartFake
    implements _i2.EmployeeAccountDaoController {
  _FakeEmployeeAccountDaoController_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ManageEmployeeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockManageEmployeeRepository extends _i1.Mock
    implements _i3.ManageEmployeeRepository {
  MockManageEmployeeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EmployeeAccountDaoController get employeeAccountDaoController =>
      (super.noSuchMethod(
        Invocation.getter(#employeeAccountDaoController),
        returnValue: _FakeEmployeeAccountDaoController_0(
          this,
          Invocation.getter(#employeeAccountDaoController),
        ),
      ) as _i2.EmployeeAccountDaoController);

  @override
  _i4.Future<bool> addEmployee(_i5.ManageEmployeeConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #addEmployee,
          [config],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateEmployee(
    _i5.ManageEmployeeConfig? config, {
    required int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEmployee,
          [config],
          {#id: id},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i6.EmployeeAccountDao?> searchByName(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByName,
          [name],
        ),
        returnValue: _i4.Future<_i6.EmployeeAccountDao?>.value(),
      ) as _i4.Future<_i6.EmployeeAccountDao?>);

  @override
  _i4.Future<List<_i6.EmployeeAccountDao>> getAllEmployeeAccountData() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllEmployeeAccountData,
          [],
        ),
        returnValue: _i4.Future<List<_i6.EmployeeAccountDao>>.value(
            <_i6.EmployeeAccountDao>[]),
      ) as _i4.Future<List<_i6.EmployeeAccountDao>>);

  @override
  _i4.Future<bool> deleteSelectedEmployee(
          _i6.EmployeeAccountDao? employeeAccount) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSelectedEmployee,
          [employeeAccount],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
