include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/**.g.dart

  errors:
    missing_default_value_for_parameter: info
    argument_type_not_assignable: ignore
    no_leading_underscores_for_local_identifiers: ignore
    sort_pub_dependencies: ignore

linter:
  rules:
    type_annotate_public_apis: false
    use_setters_to_change_properties: false
    avoid_positional_boolean_parameters: false
    avoid_classes_with_only_static_members: false
    avoid_dynamic_calls: false
    avoid_unused_constructor_parameters: false

