name: Build and Distribute Flutter App

on:
  push:
    branches:
      - feature/ci-cd_implementation

jobs:
  build:
    name: Build & Distribute
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.1

      - name: Install dependencies
        run: flutter pub get

      - name: Set up Firebase CLI
        uses: w9jds/firebase-action@v2.2.0
        with:
          args: --version
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/android_app-key.jks

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release --build-name=1.0.0 --build-number=${{ github.run_number }}
        env:
          KEYSTORE_PASSWORD: ${{ vars.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ vars.KEY_ALIAS }}
          KEY_PASSWORD: ${{ vars.KEY_PASSWORD }}

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk
          releaseNotes: "CI Release"